package com.boxing.bracket.audit.domain;

public enum AuditActionType {
    BOUT_STARTED,
    BOUT_STATUS_CHANGED,
    ROUND_STARTED,
    NEXT_BOUT_READY,
    SCORE_SUBMITTED,
    PENALTY_CREATED,
    RESULT_CONFIRMED,
    BOUT_CREATED,
    BOUT_UPDATED,
    BOUT_DELETED,
    BOUT_IMPORTED,
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DELETED,
    ASSIGNMENT_CREATED,
    ASSIGNMENT_UPDATED,
    NOTICE_CREATED,
    NOTICE_UPDATED,
    NOTICE_DELETED,
    SCHEDULE_CREATED,
    SCHEDULE_UPDATED,
    SCHEDULE_DELETED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    LOGOUT
}
