-- Historical pointer. Do not execute this file directly.
-- The staff assignment table, constraint, and indexes are part of the versioned baseline:
-- back/src/main/resources/db/migration/V1__create_initial_schema.sql
